services:
  - type: web
    name: booking-master
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ADMIN_TOKEN
        generateValue: true
      - key: DB_URL
        fromDatabase:
          name: booking-master-db
          property: connectionString

databases:
  - name: booking-master-db
    databaseName: bookingmaster
    user: bookingmaster
    plan: free
    region: oregon
    postgresMajorVersion: "17"
    ipAllowList: []