spring.application.name=booking-master

spring.datasource.url=jdbc:${DB_URL:postgresql://bookingmaster:bookingmaster@localhost:5433/bookingmaster}
spring.sql.init.mode=always


#server
server.port=${PORT:8080}

#acturator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:40}
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000

app.hold-minutes=10
app.expiry-interval-ms=5000
app.admin-token=${ADMIN_TOKEN:admin}

logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG